image: node:lts
pages:
  stage: deploy
  cache:
    key:
      files:
        - my-vue-app/package-lock.json
      prefix: npm
    paths:
      - my-vue-app/node_modules/
  script:
    - cd my-vue-app
    - npm install
    - npm run build
    - cp -a dist/. public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH